[project]
authors = ["Bryn Pickering <17178478+brynpickering@users.noreply.github.com>", "Markus Groissböck <markus.groissbock@openenergytransition.org>"]
channels = ["conda-forge"]
name = "open-esm-analysis"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
get-tools = {cmd = "python $PIXI_PROJECT_ROOT/inventory/get_tools.py inventory/output/tools.csv",inputs = ["inventory/get_tools.py"], outputs = ["inventory/output/tools.csv"]}
filter-tools = {cmd = "python $PIXI_PROJECT_ROOT/inventory/filter_tools.py inventory/output/tools.csv inventory/output/filtered.csv", inputs = ["inventory/output/tools.csv", "inventory/filter_tools.py"], outputs = ["inventory/output/filtered.csv"], depends-on = ["get-tools"]}
get-stats = {cmd = "python $PIXI_PROJECT_ROOT/inventory/get_stats.py inventory/output/filtered.csv inventory/output/stats.csv", inputs = ["inventory/output/filtered.csv", "inventory/get_stats.py"], outputs = ["inventory/output/stats.csv"], depends-on = ["filter-tools"]}

[dependencies]
pandas = ">=2.2.3,<3"
requests = ">=2.32.3,<3"
ipython = ">=9.2.0,<10"
pandas-stubs = ">=2.2.3.250308,<3"
click = ">=8.2.1,<9"
yaml = ">=0.2.5,<0.3"
pyyaml = ">=6.0.2,<7"
tqdm = ">=4.67.1,<5"
ipdb = ">=0.13.13,<0.14"
pyarrow = ">=20.0.0,<21"
tabulate = ">=0.9.0,<0.10"
bs4 = ">=4.13.4,<5"
pre-commit = ">=4.2.0,<5"

[feature.app.dependencies]
itables = "*"
streamlit = "*"


[feature.app.tasks]
serve = "streamlit run $PIXI_PROJECT_ROOT/website/streamlit_app.py"

[feature.vis.dependencies]
plotly = "*"
matplotlib = "*"
seaborn = "*"

[environments]
app = ["app"]
vis = ["vis"]
